// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Pzo_um3NJBTR4PX81HG7R9XzGLgZfW8',
    appId: '1:776782980237:web:c489c8f5228f1f1ebdaec4',
    messagingSenderId: '776782980237',
    projectId: 'bigbran-62b09',
    authDomain: 'bigbran-62b09.firebaseapp.com',
    storageBucket: 'bigbran-62b09.appspot.com',
    measurementId: 'G-SEEK5B5Z24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsDgA8Yj7fgZxbKn-cbN2x4Nnl3n6aEHA',
    appId: '1:776782980237:android:19f0c2ded51bb366bdaec4',
    messagingSenderId: '776782980237',
    projectId: 'bigbran-62b09',
    storageBucket: 'bigbran-62b09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcIbd3VM5QTW7n-8_t18euK3eam3wBy9A',
    appId: '1:776782980237:ios:e4c4e5ba8d7bbb00bdaec4',
    messagingSenderId: '776782980237',
    projectId: 'bigbran-62b09',
    storageBucket: 'bigbran-62b09.appspot.com',
    iosClientId: '776782980237-821ggdr0gqall217pgt8a695ktju7fol.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcIbd3VM5QTW7n-8_t18euK3eam3wBy9A',
    appId: '1:776782980237:ios:39519f169d46937fbdaec4',
    messagingSenderId: '776782980237',
    projectId: 'bigbran-62b09',
    storageBucket: 'bigbran-62b09.appspot.com',
    iosClientId: '776782980237-hivk8p9hrj83cso7dg6mvonf7re4ue28.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate.RunnerTests',
  );
}
